apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "27823939"
    labels:
        datastore_id: "5049508459184128"
data:
    classification: Serious Bug
    created: "2016-08-12T15:39:57.67292Z"
    description: |-
        Summary:
        I’ll be on a wi-fi call, which is going fine, and I’ll have a second call come in. After taking that second call, the first call fails.

        Steps to Reproduce:
        1. Place call with the FaceTime app using wi-fi calling, talking for a few minutes
        2. Receive a second call
        3. Click “Hold & Accept”
        4. Talk for a few minutes
        5. End the new call, either by clicking “End” or the switch-to-other-line button

        Expected Results:
        Second call ends (or holds) and original call resumes

        Actual Results:
        The original call appears to be active, but neither party can hear each other, and eventually the call fails

        Regression:

        Notes:
        My phone is an iPhone 6, in case that matters. While this happened a couple times, I had the Wireless Diagnostics tool running (for a different issue), and it detected no issues
    email: thedov@gmail.com
    modified: "2016-08-12T15:39:57.6731Z"
    number: "27823939"
    number_intvalue: 27823939
    originated: 12-Aug-2016 11:39 AM
    parent_number: '&{NULL_VALUE}'
    product: OS X
    product_version: Mac OS X 10.11.5 (15F34)
    reproducible: Sometimes
    resolved: ""
    status: Open
    title: 'Mac OS X 10.11.5: Call over wi-fi calling fails after accepting a second call'
