apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "21409580"
    labels:
        datastore_id: "5525043815645184"
data:
    classification: ""
    created: "2015-06-16T21:28:39.79387Z"
    description: "Summary:\r\nXCTFail seems to not close the control-flow for a do/try/catch.\r\n\r\nSee also, this conversation: https://twitter.com/jckarter/status/610915030553374720\r\n\r\nSteps to Reproduce:\r\n1. git clone https://github.com/eliperkins/JSONCodable/ from this commit: bd4aa07e9c8b964a7a6c3ab0178a38cc52b31faa\r\n2. See JSONCodableTests.swift\r\n3. Note how accessing `dict` later causes errors with accessing an uninitialized variable\r\n\r\nExpected Results:\r\nI can access dict after the do/try/catch since XCTFail\r\n\r\nActual Results:\r\nI can't access dict without adding fatalError to close the control path. Adding fatalError() inside the catch will suppress any errors.\r\n\r\nVersion:\r\nXcode Version 7.0 beta (7A120f)\r\nOS X Yosemite 10.10.4 (14E33b)"
    email: eli.j.perkins@gmail.com
    modified: "2015-06-29T14:16:09.54481Z"
    number: "21409580"
    number_intvalue: 21409580
    originated: 16-Jun-2015 05:24 PM
    parent_number: '&{NULL_VALUE}'
    product: Developer Tools
    product_version: ""
    reproducible: Yes
    resolved: ""
    status: Closed (Duplicate)
    title: XCTFail not closing control-flow with do/try/catch
