apiVersion: openapi/v1alpha1
kind: Radar
metadata:
    name: "15323284"
    labels:
        datastore_id: "6338886397591552"
data:
    classification: Serious Bug
    created: "2013-10-25T21:21:52.22302Z"
    description: "Summary:\r\nOpenVPN recently added support for OS X's utun devices for layer 3 tunneling. On some 10.9 systems, the call to connect() fails with an errno of ENOBUFS. We have never seen this or any similar failure on 10.8.\r\n\r\nWe'll update this if we manage to narrow down the circumstances at all.\r\n\r\nSteps to Reproduce:\r\n1. Attempt to allocate a utun device on an afflicted machine. (Code would look similar to https://github.com/bbits/openvpn-utun/blob/utun/src/openvpn/tun.c#L2488).\r\n\r\nExpected Results:\r\nconnect() returns 0 and allocates an available utun device.\r\n\r\nActual Results:\r\nconnect() returns -1 with an errno of ENOBUFS.\r\n\r\nVersion:\r\n10.9\r\n\r\nNotes:\r\nWe've been able to contact one customer reporting this issue. Restarting their machine did not improve the situation."
    email: peter.sagerson@gmail.com
    modified: "2013-10-25T21:21:52.223172Z"
    number: "15323284"
    number_intvalue: 15323284
    originated: 10/25/13
    parent_number: '&{NULL_VALUE}'
    product: OS X
    product_version: "10.9"
    reproducible: Rarely
    resolved: ""
    status: Open
    title: Creating a utun device occasionally returns ENOBUFS on 10.9
